apiVersion: v1
kind: Service
metadata:
  name: "{{ name }}"
  labels:
    app: "{{ name }}"
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
    - port: 443
      protocol: TCP
      targetPort: 8443
      name: https
  selector:
    app: "{{ name }}"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ name }}"
spec:
  selector:
    matchLabels:
      app: "{{ name }}"
  replicas: 2
  template:
    metadata:
      labels:
        app: "{{ name }}"
    spec:
      containers:
        - name: "{{ name }}"
          image: "jecklgamis/{{ name }}:{{ version }}"
          ports:
            - containerPort: 8080
            - containerPort: 8443

